name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  resourceGroupName:  # id of input
    description: 'Name of the resource group'
    required: true
    default: 'World'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'node16'
  main: 'index.js'